### ISSUE TITLE
test_processing_data doesn't test preprocessing

### ISSUE THREAD

**Issue by emilyps14** [catalystneuro/ecogVIS#101]
The test suite for preprocessing, `test_processing_data`, hard codes the LFP in the nwb file. As a result, `preprocess_raw_data` does not run any preprocessing and the downsampling, CAR, and notch filtering are never tested. 

(This is why no one noticed that the notch filtering step wasn't happening, Issue #99)

I would like to refactor the test case, but I need your help:
1. Setting up the nwb object with raw data will take more space. Ideally I would like to use 1 second of data sampled at 3051.75 (our typical sampling rate). This looks unwieldy if I copy it into the code. Is it ok to put it in a csv? Due to downsampling, the "expected" data will be 401 rows for each of the tests (could be in csv or copied into the code)
2. Starting from the raw data introduces dependencies between the tests (high gamma and decomposition can't be run until after preprocessing). One possibility is to combine the tests as suggested here: https://stackoverflow.com/questions/5387299/python-unittest-testcase-execution-order. Would that be ok, or would you prefer a different architecture?

**Comment by luiztauffer** [comment]
fixed with #100
