### ISSUE TITLE
Unnecessary package?

### ISSUE THREAD

**Issue by jrliu95** [catalystneuro/ecogVIS#109]
@luiztauffer  I couldn't find a reference to the `tdt` package in this repo (there shouldn't be any need for it), so I'm not sure why a version is hard coded in here (which could affect versions in our own code). Can you remove it unless there's a reason it should be there?

https://github.com/catalystneuro/ecogVIS/blob/c4ea9aaf05b427ec28b9eea21496ca694a2b9b56/requirements.txt#L20

**Comment by bendichter** [comment]
removed
