### ISSUE TITLE
rebrand

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/ecogVIS#52]
I'd like to rebrand this to be more general, to be used for extracellular electrophysiology more broadly

1) rename. Any ideas?
2) interface with SpikeInterface to provide access to spike sorters. Maybe via spikely

**Comment by luiztauffer** [comment]
ephysVIS?

**Comment by bendichter** [comment]
Too close to https://github.com/flatironinstitute/ephys-viz, though maybe it would make sense to build upon that project

**Comment by luiztauffer** [comment]
@bendichter can we close this?
