### ISSUE TITLE
Audio Event Detection GUI doesn't reflect jgmakin/ecogVIS updates

### ISSUE THREAD

**Issue by emilyps14** [catalystneuro/ecogVIS#82]
PR #76  was supposed to merge in changes from the changlab fork, but (at least) the Audio Event Detection GUI does not seem to have the design updates.

**Comment by luiztauffer** [comment]
@emilyps14 would you mind naming the design updates you’re missing, perhaps with a screenshot?
I tried to run `jgmakin/ecogVIS` with the `EC208_B2.nwb` file, but the old code lacks some changes to identify the mic recordings and I can’t open the CV Event Detector.

**Comment by emilyps14** [comment]
I'm having trouble getting the updated master branch to work for comparison but in the meantime here is what the jgmakin version looks like: 
<img width="1212" alt="Screen Shot 2020-05-09 at 11 39 41 AM" src="https://user-images.githubusercontent.com/4949989/81482468-1b076400-91ec-11ea-88a2-622b7053722e.png">

**Comment by emilyps14** [comment]
Some important features:
1. Separate thresholds for speaker and mic
2. Distinction between detection window and plotting window, and ability to omit times at the beginning and end of the recording (setting the detection window)
3. Showing the smooth traces and the threshold level in the window

Are these features in the most recent catalystneuro/ecogVIS master? I'm not seeing them, but maybe there's something wrong on my end

**Comment by luiztauffer** [comment]
hi @emilyps14 , thank you for the PR! I tried it here and it seems to be ok, but I don't have microphone signals (only noise), so I can't check if every detail is looking really how it should. Could you try to reproduce this with the current mater branch and see if this Issue can be closed?

**Comment by emilyps14** [comment]
Here is a screenshot of the same settings and data I used above, using the current master branch:
<img width="1212" alt="Screen Shot 2020-06-11 at 9 46 52 AM" src="https://user-images.githubusercontent.com/4949989/84416167-b2375100-abc8-11ea-9e3a-9bf77b33bd45.png">
