### ISSUE TITLE
Audio Event Detection "Run Test" button crashes ecogVIS app on click 

### ISSUE THREAD

**Issue by emilyps14** [catalystneuro/ecogVIS#83]
> Traceback (most recent call last):
>   File ".../ecogvis/functions/audio_event_detection.py", line 294, in run
>     direction='both'
> TypeError: detect_events() got an unexpected keyword argument 'threshold'
> Abort trap: 6

**Comment by luiztauffer** [comment]
hi @emilyps14 
it was a small error, thanks for pointing it! It should be fixed now
