### ISSUE TITLE
ecogVIS main plot, axes ticks not properly aligned

### ISSUE THREAD

**Issue by kristinksellers** [catalystneuro/ecogVIS#84]
x- and y-axis ticks do not appear to scale/align appropriately

Running ecogvis from Jupyter notebook, on a Windows 10 machine

![ecogVIS_screenshot](https://user-images.githubusercontent.com/3281849/81436556-8b47b400-911e-11ea-86ff-b6788e1851e5.png)

**Comment by luiztauffer** [comment]
@kristinksellers I tried to reproduce with the same file here, but it's working fine on my end.
I think you're using an older version, can you try it with the current repo version and let me know if the problem persists?

```shell
$ conda activate your_env_name
$ pip install git+https://github.com/catalystneuro/ecogVIS.git 
```

**Comment by kristinksellers** [comment]
@luiztauffer This resolved the problem - thanks!
