### ISSUE TITLE
Cannot run ecogvis from Jupyter notebook

### ISSUE THREAD

**Issue by kristinksellers** [catalystneuro/ecogVIS#86]
![image](https://user-images.githubusercontent.com/3281849/82011342-95d7e100-9629-11ea-9270-05f5eefc263d.png)

**Comment by kristinksellers** [comment]
I got the latest version of ecogVIS from github, but am still running into this problem:

![image](https://user-images.githubusercontent.com/3281849/83554141-271bd400-a4c1-11ea-8096-61e01cc69d7d.png)

**Comment by luiztauffer** [comment]
@kristinksellers that's strange, I can't reproduce the error, your code runs correctly on my machine.
Can you please uninstall ecogvis and install it again in your environment?
It reminded me that I forgot to publish on pypi, I'll do that today to make things easier

**Comment by luiztauffer** [comment]
@kristinksellers can you confirm this problem is still happening with the most current version on your environment?

**Comment by kristinksellers** [comment]
@luiztauffer Problem resolved - thanks!
