### ISSUE TITLE
Notch filtering operates on the channels dimension rather than the time dimension

### ISSUE THREAD

**Issue by emilyps14** [catalystneuro/ecogVIS#99]
Possibly due to an error in the documentation for `nwb_process` (see https://github.com/BouchardLab/process_nwb/issues/8), the notch filtering step in `ecogvis.signal_processing.processing_data` was operating on the wrong dimension of the data. As a result, 
1. The notch filtering effectively didn't occur, and
2. The channels dimension was padded by 2*Fs, in my case increasing the size of the data by a factor of 800. This made the preprocessing massively inefficient. (Fixing the error took the runtime of the notch filtering step from 7000s to 2.5s on a normal-sized dataset, using my laptop)

I have a pull request that fixes this error.

**Comment by luiztauffer** [comment]
fixed with #100
